[versions]
kotlin = "2.0.0"
ktor = "2.3.11"
kotlinx-coroutines = "1.8.1"
spring-boot = "3.3.0"
spring-deps = "1.1.5"
spring-security-crypto = "6.3.0"
flyway = "10.13.0"
graalvm = "0.10.1"
slf4j = "2.0.13"
logback = "1.5.6"
bcprov = "1.78.1"
javafaker = "1.0.2"
#flink = "1.18.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-deps = { id = "io.spring.dependency-management", version.ref = "spring-deps" }
flyway-db = { id = "org.flywaydb.flyway", version.ref = "flyway" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm" }

[libraries]
# Gradle Plugin for build-logic
plugin-kotlin-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
plugin-kotlin-spring = { group = "org.jetbrains.kotlin", name = "kotlin-allopen", version.ref = "kotlin" }
plugin-kotlin-jpa = { group = "org.jetbrains.kotlin", name = "kotlin-noarg", version.ref = "kotlin" }
plugin-ktor = { group = "io.ktor.plugin", name = "plugin", version.ref = "ktor" }
plugin-spring-boot = { group = "org.springframework.boot", name = "spring-boot-gradle-plugin", version.ref = "spring-boot" }
plugin-spring-deps = { group = "io.spring.gradle", name = "dependency-management-plugin", version.ref = "spring-deps" }
plugin-flyway-db = { group = "gradle.plugin.org.flywaydb", name = "gradle-plugin-publishing", version.ref = "flyway" }
plugin-graalvm-native = { group = "org.graalvm.buildtools.native", name = "org.graalvm.buildtools.native.gradle.plugin", version.ref = "graalvm" }

# Kotlin Language

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlin-jackson = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }

kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# Ktor

ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor" }
ktor-server-auto-head-response = { group = "io.ktor", name = "ktor-server-auto-head-response", version.ref = "ktor" }
ktor-server-method-override = { group = "io.ktor", name = "ktor-server-method-override", version.ref = "ktor" }
ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-sessions = { group = "io.ktor", name = "ktor-server-sessions", version.ref = "ktor" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-curl = { group = "io.ktor", name = "ktor-client-curl", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { group = "io.ktor", name = "ktor-client-json", version.ref = "ktor" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
ktor-client-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Spring Framework

spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter" }
spring-boot-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-logging = { group = "org.springframework.boot", name = "spring-boot-starter-logging" }
spring-boot-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux" }
spring-boot-graphql = { group = "org.springframework.boot", name = "spring-boot-starter-graphql" }
spring-boot-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-r2dbc = { group = "org.springframework.boot", name = "spring-boot-starter-data-r2dbc" }
spring-boot-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-data-jdbc" }
spring-boot-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-session = { group = "org.springframework.session", name = "spring-session-jdbc" }
spring-boot-json = { group = "org.springframework.boot", name = "spring-boot-starter-json" }
spring-boot-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }

spring-security-crypto = { group = "org.springframework.security", name = "spring-security-crypto", version.ref = "spring-security-crypto" }
spring-security-test = { group = "org.springframework.security", name = "spring-security-test" }

# Database

db-flyway = { group = "org.flywaydb", name = "flyway-core" }
db-hikari = { group = "com.zaxxer", name = "HikariCP" }

db-pg = { group = "org.postgresql", name = "postgresql" }
db-h2 = { group = "com.h2database", name = "h2" }

db-testcontainers = { group = "org.testcontainers", name = "testcontainers" }
db-testcontainers-pg = { group = "org.testcontainers", name = "postgresql" }
db-testcontainers-junit = { group = "org.testcontainers", name = "junit-jupiter" }

## JPA

jpa-pg = { group = "org.postgresql", name = "postgresql" }
jpa-h2 = { group = "com.h2database", name = "h2" }

## R2DBC

r2dbc-pg = { group = "org.postgresql", name = "r2dbc-postgresql" }

# Logging

logging-slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref ="slf4j" }
logging-logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# Crypto

crypto-bcprov = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bcprov" }

# Test

test-faker = { group = "com.github.javafaker", name = "javafaker", version.ref = "javafaker" }

# Flink

#flink-java = { group = "org.apache.flink", name = "flink-java", version.ref = "flink" }
#flink-streaming-java = { group = "org.apache.flink", name = "flink-streaming-java", version.ref = "flink" }
#flink-clients = { group = "org.apache.flink", name = "flink-clients", version.ref = "flink" }
#flink-connector-files = { group = "org.apache.flink", name = "flink-connector-files", version.ref = "flink" }

[bundles]
spring-plugin = [
    "plugin-kotlin-jvm",
    "plugin-kotlin-spring",
    "plugin-kotlin-jpa",
    "plugin-spring-boot",
    "plugin-spring-deps",
    "plugin-flyway-db",
]
spring-kotlin = [
    "kotlin-stdlib",
    "kotlin-reflect",
    "spring-boot-starter",
]
spring-web = [
    "spring-boot-web",
    "spring-boot-graphql",
]
spring-security = [
    "spring-boot-security",
    "spring-boot-session",
    "spring-boot-jpa",
]
spring-json = [
    "spring-boot-json",
    "kotlin-jackson",
]
db-h2 = [
    "db-h2"
]
db-pg = [
    "db-testcontainers",
    "db-testcontainers-pg",
    "db-hikari",
    "db-pg",
]
r2dbc-pg = [
    "spring-boot-r2dbc",
    "r2dbc-pg"
]
ktor-server-jvm = [
    "ktor-server-core",
    "ktor-server-netty",
]
ktor-server-native = [
    "kotlinx-coroutines",
    "ktor-server-core",
    "ktor-server-cio",
]
ktor-client-native = [
    "kotlinx-coroutines",
    "ktor-client-core",
    "ktor-client-curl",
    "ktor-client-content-negotiation",
    "ktor-client-serialization",
    "ktor-client-serialization-json",
]
slf4j = [
    "logging-slf4j",
    "logging-logback"
]
test-containers = [
    "db-testcontainers",
    "db-testcontainers-pg",
    "db-testcontainers-junit",
]
#flink = [
#    "flink-java",
#    "flink-streaming-java",
#    "flink-clients",
#    "flink-connector-files",
#]
