[versions]
kotlin = "2.0.0"
kotlinx-io = "0.5.0"
clikt = "4.4.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
kotlinx-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
utils-clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }
